### ISSUE TITLE
Integrate Welcome and Greeting Bot 

### ISSUE THREAD

**Issue by akrish4** [rajpratyush/Social-Distancing-Detector#1]
Hi @rajpratyush 

I would like to contribute to this amazing project
I can add a config file and integrate the bot so that whenever a new user opens a issue or pr , the bot will comment and greet the user with a proper message

Let me know if you are interested

Kindly do assign me
Kindly do add the DWOC and Level label

**Comment by akrish4** [comment]
thank you @rajpratyush 
Kindly do add the DWOC  and  Level  label as this is a feature update to the repository

**Comment by akrish4** [comment]
even this is also minor ?

**Comment by rajpratyush** [comment]
Yes I had talked to other maintainers as well and as per code.of conduct these are minor documentation fixes as you just integrating the bot

**Comment by akrish4** [comment]
okay fine
