### ISSUE TITLE
readme needs to be updated

### ISSUE THREAD

**Issue by Sloth-Panda** [rajpratyush/Social-Distancing-Detector#11]
the images in the readme are not working fine, and readme can be improved by adding emojis and making better layout

**Comment by rajpratyush** [comment]
You can go for it but still it is a minor documentation fix so I will label as level 1

**Comment by Sloth-Panda** [comment]
@rajpratyush  can you tell me what to use for images that are not showing up in the readme?

**Comment by rajpratyush** [comment]
actually the images hasnt been uploaded into the  images folder and that's why it is not showing up

**Comment by Sloth-Panda** [comment]
okay can you assign to me
