### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Vrushti24** [rajpratyush/Social-Distancing-Detector#17]
**Is your documentation issue related to a problem? Please describe.**
I saw that these project does not contain lincense 
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
I can add license lke MIT 
- A clear and concise description of what you want to happen.
Each and every project have license but this does not have so we have to add a licence
- Add any other context or screenshots about the issue here.

**Comment by Vrushti24** [comment]
I can work on this issue

**Comment by rajpratyush** [comment]
@Vrushti24 sure you can work on this issue

**Comment by Vrushti24** [comment]
Hey @rajpratyush please check PR #18 . It is MIT license

**Comment by rajpratyush** [comment]
@Vrushti24 just a tip that i would suggest before putting out a PR just use keywords like closes or fixed and then mention the issue number using # followed by issue number so that it will automatically close the issue.

**Comment by Vrushti24** [comment]
Thanks, I'll check it out.

**Comment by rajpratyush** [comment]
@Vrushti24 yes it was suggested by a Repo maintainer, where I contribute actively. It's a good practice

**Comment by Vrushti24** [comment]
yeah
