### ISSUE TITLE
CONTRIBUTING FILE 

### ISSUE THREAD

**Issue by akrish4** [rajpratyush/Social-Distancing-Detector#2]
Hi @rajpratyush 
I would like to contribute to this amazing project 
I would like to add a `CONTRIBUTING.md`file which will contain all contributing guidelines and all git workflow so that all newbies or beginers and even experts can look into into it and also the contributors will understand the workflow 

Kindly do assign me 

Kindly add the labels also

**Comment by rajpratyush** [comment]
Sure @akrish4

**Comment by akrish4** [comment]
thank you @rajpratyush 
Kindly do add the DWOC  and  Level  label

**Comment by akrish4** [comment]
Hi @rajpratyush 
Let me know why have u removed Level-2 ?

**Comment by rajpratyush** [comment]
As per code of conduct these are minor documentation fixes hence I will give it a label of level 1

**Comment by akrish4** [comment]
okay

**Comment by ssg8288** [comment]
> 
> 
> Hi @rajpratyush
> Let me know why have u removed Level-2 ?

Hey, this is a repo maintainer here from dwoc see contributors can't decide what should be the level tag it totally depends on the repo maintainer what he feels is best suited for the issue also based upon the maintainer's guidelines and I can see its best suited for level 1 i.e. for minor doc work
