### ISSUE TITLE
CODE OF CONDUCT FILE 

### ISSUE THREAD

**Issue by akrish4** [rajpratyush/Social-Distancing-Detector#3]
There is no code of conduct file in this repository
code of conduct is a file that will be required to a open source project for the contributors to follow the decorum
Kindly let me know if you can assign me this issue

**Comment by rajpratyush** [comment]
sure I  can assign this issue to you

**Comment by akrish4** [comment]
thank you

**Comment by comradekingu** [comment]
> code of conduct is a file that will be required to a open source project for the contributors to follow the decorum

?

**Comment by rajpratyush** [comment]
Still its a minor documentation fix hence it is a level 1

**Comment by akrish4** [comment]
#15  PR
