### ISSUE TITLE
PR TEMPLATE 

### ISSUE THREAD

**Issue by akrish4** [rajpratyush/Social-Distancing-Detector#4]
I would like to add a pr template which will give a template and users need to fill it inorder to open a pr and maintainer will get better understanding of the pr with images

Kindly do assign me

**Comment by akrish4** [comment]
@rajpratyush I was the first one to open this issue , u can't assign it to someone else , u assigned and merged also ,

**Comment by rajpratyush** [comment]
i had assigned you this issue you didn't do even 5 minutes of work though it was just 20-30 minutes of work barely. even all the other project maintainers are have same complain against you.

**Comment by rajpratyush** [comment]
you are raising same issue in each and every repository participating in DWoC

**Comment by akrish4** [comment]
okay sorry , i was bit busy , i am working on remaining issues

**Comment by akrish4** [comment]
yes we can open similar issues as these are documentation works that , not only me , more 3 members are also working on the same type isssues only ,

**Comment by akrish4** [comment]
i am just opening issue that are of documentation type , and we can open same issues in every repository also , and its maintainer who assigns it , me or other will open this kind of docs issues , and if mainatiner don't want that docs then they close it , those who need it , they will assign thatsall
