### ISSUE TITLE
Camera Calibration

### ISSUE THREAD

**Issue by rajpratyush** [rajpratyush/Social-Distancing-Detector#6]
Camera calibration for intrinsic parameter as the only drawback of Social distance violation detection using distance formula.

**Comment by Bijay555** [comment]
@rajpratyush can you assign this to me?

**Comment by rajpratyush** [comment]
Sure @Bijay555

**Comment by rajpratyush** [comment]
Will do it on the morning itself when I will open lappy

**Comment by rajpratyush** [comment]
@Bijay555  just a tip that i would suggest before putting out a PR just use keywords like closes or fixed and then mention the issue number using # followed by issue number so that it will automatically close the issue.

**Comment by rajpratyush** [comment]
and would you like to take up #8
