### ISSUE TITLE
Add Contributors Table in README.md

### ISSUE THREAD

**Issue by samir-0711** [rajpratyush/Social-Distancing-Detector#7]
Like this
![image](https://user-images.githubusercontent.com/68433936/104812445-2ce3e100-5828-11eb-8663-615997dc8dea.png)

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by rajpratyush** [comment]
Can you explain bit more ?

**Comment by samir-0711** [comment]
I will add table in README.md file which will show all contributors of this project. And it will be automated.

**Comment by rajpratyush** [comment]
Okay i will assign this
